apiVersion: v1
kind: Service
metadata:
  name: djangok8s-service
spec:
  selector:
    app: djangos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 31000
  type: NodePort 
